const defaultToolbox = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'CATEGORY',
      contents: [
        {kind: 'BLOCK', type: 'loops_repeat'},
        {kind: 'BLOCK', type: 'loops_while_until'},
        {kind: 'BLOCK', type: 'loops_for'},
      ],
      name: 'Loops',
      colour: '120',
    },
    {
      kind: 'CATEGORY',
      contents: [
        {kind: 'BLOCK', type: 'http_request'},
        {kind: 'BLOCK', type: 'sparql_query'},
        {kind: 'BLOCK', type: 'sparql_ask'},
        {kind: 'BLOCK', type: 'display_text'},
        {kind: 'BLOCK', type: 'display_table'},
        {kind: 'BLOCK', type: 'table_cell'},
        {kind: 'BLOCK', type: 'switch_lights'},
        {kind: 'BLOCK', type: 'random_sound'},
        {kind: 'BLOCK', type: 'break_continue'},
        {kind: 'BLOCK', type: 'wait_seconds'},
      ],
      name: 'Actions',
      colour: '0',
    },
    {
      kind: 'CATEGORY',
      contents: [
        {kind: 'BLOCK', type: 'conditional_statement'},
        {kind: 'BLOCK', type: 'event'},
        {kind: 'BLOCK', type: 'logic_compare'},
        {kind: 'BLOCK', type: 'logic_operation'},
        {kind: 'BLOCK', type: 'logic_negate'},
      ],
      name: 'Conditions',
      colour: '210',
    },
    {
      kind: 'sep',
      gap: '32',
    },
    {
      kind: 'CATEGORY',
      contents: [
        {kind: 'BLOCK', type: 'uri'},
        {kind: 'BLOCK', type: 'mac'},
        {kind: 'BLOCK', type: 'text'},
        {kind: 'BLOCK', type: 'text_join'},
        {kind: 'BLOCK', type: 'text_length'},
        {kind: 'BLOCK', type: 'text_indexOf'},
        {kind: 'BLOCK', type: 'text_charAt'},
        {kind: 'BLOCK', type: 'text_getSubstring'},
        {kind: 'BLOCK', type: 'text_changeCase'},
        {kind: 'BLOCK', type: 'text_replace'},
      ],
      name: 'Text',
      colour: '160',
    },
    {
      kind: 'CATEGORY',
      contents: [
        {kind: 'BLOCK', type: 'number_value'},
        {kind: 'BLOCK', type: 'number_infinity'},
        {kind: 'BLOCK', type: 'number_arithmetic'},
        {kind: 'BLOCK', type: 'number_random'},
      ],
      name: 'Numbers',
      colour: '230',
    },
    {
      kind: 'CATEGORY',
      contents: [{kind: 'BLOCK', type: 'logic_boolean'}],
      name: 'Booleans',
      colour: '210',
    },
    {
      kind: 'sep',
      gap: '32',
    },
    {
      kind: 'CATEGORY',
      contents: [],
      name: 'Variables',
      custom: 'VARIABLE',
      colour: '330',
    },
    {
      kind: 'CATEGORY',
      contents: [],
      name: 'Functions',
      colour: '290',
      custom: 'PROCEDURE',
    },
  ],
};
