nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpIgnorePatterns:
  - ./packages/**

yarnPath: .yarn/releases/yarn-3.5.1.cjs
