name: Licenses Summary

# Controls when the action will run.
on: [push, pull_request]

jobs:
  licenses-summary:
    name: Licenses summary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Yarn
        id: setup-yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        id: yarn-install
        run: yarn install

      - name: Get Licenses
        id: get-licenses
        run: echo licenses=$(yarn licenses list --json | yarn ndjson-reduce) >> $GITHUB_OUTPUT

      - name: Create Licenses Summary
        id: create-summary
        uses: derwehr/yarn-licenses-summary@v1
        with:
          licenses: ${{ steps.get-licenses.outputs.licenses }}
