name: Lint and Deploy

# Controls when the action will run. 
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      # Use cache for node modules
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --ignore-engines
      - name: run ESLint
        run: yarn run lint
  build-examples:
    runs-on: ubuntu-latest
    needs: lint
      
    steps:
        - uses: actions/checkout@master
        # Use cache for node modules
        - uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        - name: yarn run build
          run: |
                cd ./examples/web
                yarn install
                yarn run build
  deploy:
    runs-on: ubuntu-latest
    needs: build-examples
    if: github.ref == 'refs/heads/master'
  
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          rm: true
          source: "./examples/web/"
          target: "./public_html/testing/blast/"
          strip_components: 2
  deploy_ren:
    runs-on: ubuntu-latest
    needs: build-examples
    if: github.ref == 'refs/heads/ren'
  
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./examples/web/"
          target: "./public_html/testing/ren/"
          strip_components: 2
  jsdocs:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@master
      # Use cache for node modules
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --ignore-engines
      - name: Run JSDoc
        run: yarn run jsdoc
