name: Lint and Deploy

# Controls when the action will run.
on: [push, pull_request]

jobs:
  lint-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: packages/web/build/
  deploy:
    runs-on: ubuntu-latest
    needs: lint-build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
        with:
          # This allows yarn workspaces --since to compare with origin/main branch
          fetch-depth: 0
      - name: download build files
        uses: actions/download-artifact@v3
        with:
          name: build
          path: packages/web/build/
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          rm: true
          strip_components: 4
          source: "./packages/web/build/"
          target: "./public_html/testing/blast/"
